use rand::Rng;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BotanicalGrowthForm {
    RosetteHerb,
    OrchardTree,
    StoneFruitTree,
    CitrusTree,
    GrassClump,
    FloatingAquatic,
    SubmergedAquatic,
}

#[derive(Debug, Clone, Copy)]
pub struct BotanicalSpeciesProfile {
    pub taxonomy_id: u32,
    pub common_name: &'static str,
    pub scientific_name: &'static str,
    pub growth_form: BotanicalGrowthForm,
    pub symbolic_chromosomes: u8,
    pub max_height_mm: f32,
    pub canopy_radius_mm: f32,
    pub root_radius_mm: f32,
    pub leaf_efficiency: f32,
    pub root_uptake_efficiency: f32,
    pub water_use_efficiency: f32,
    pub volatile_scale: f32,
    pub fruiting_threshold: f32,
    pub litter_turnover: f32,
    pub shade_tolerance: f32,
    pub root_depth_bias: f32,
    pub symbiosis_affinity: f32,
    pub seed_mass: f32,
    pub fruit_rgb: [f32; 3],
    pub wood_density: f32,
    pub drag_coefficient: f32,
    pub stem_diameter_fraction: f32,
}

pub const ARABIDOPSIS_THALIANA: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 3702,
    common_name: "Thale cress",
    scientific_name: "Arabidopsis thaliana",
    growth_form: BotanicalGrowthForm::RosetteHerb,
    symbolic_chromosomes: 5,
    max_height_mm: 10.0,
    canopy_radius_mm: 4.2,
    root_radius_mm: 3.4,
    leaf_efficiency: 1.22,
    root_uptake_efficiency: 0.92,
    water_use_efficiency: 0.84,
    volatile_scale: 0.72,
    fruiting_threshold: 0.78,
    litter_turnover: 0.88,
    shade_tolerance: 0.64,
    root_depth_bias: 0.24,
    symbiosis_affinity: 0.78,
    seed_mass: 0.040,
    fruit_rgb: [0.72, 0.80, 0.34],
    wood_density: 150.0,
    drag_coefficient: 0.6,
    stem_diameter_fraction: 0.08,
};

pub const MALUS_DOMESTICA: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 3750,
    common_name: "Apple",
    scientific_name: "Malus domestica",
    growth_form: BotanicalGrowthForm::OrchardTree,
    symbolic_chromosomes: 17,
    max_height_mm: 18.0,
    canopy_radius_mm: 8.0,
    root_radius_mm: 5.8,
    leaf_efficiency: 1.08,
    root_uptake_efficiency: 0.96,
    water_use_efficiency: 0.88,
    volatile_scale: 1.22,
    fruiting_threshold: 0.74,
    litter_turnover: 1.02,
    shade_tolerance: 1.00,
    root_depth_bias: 0.62,
    symbiosis_affinity: 1.08,
    seed_mass: 0.120,
    fruit_rgb: [0.86, 0.18, 0.12],
    wood_density: 650.0,
    drag_coefficient: 0.45,
    stem_diameter_fraction: 0.12,
};

pub const PYRUS_COMMUNIS: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 23211,
    common_name: "Pear",
    scientific_name: "Pyrus communis",
    growth_form: BotanicalGrowthForm::OrchardTree,
    symbolic_chromosomes: 17,
    max_height_mm: 18.5,
    canopy_radius_mm: 8.4,
    root_radius_mm: 6.0,
    leaf_efficiency: 1.04,
    root_uptake_efficiency: 0.97,
    water_use_efficiency: 0.90,
    volatile_scale: 1.10,
    fruiting_threshold: 0.76,
    litter_turnover: 0.98,
    shade_tolerance: 0.94,
    root_depth_bias: 0.60,
    symbiosis_affinity: 1.02,
    seed_mass: 0.118,
    fruit_rgb: [0.78, 0.68, 0.22],
    wood_density: 620.0,
    drag_coefficient: 0.46,
    stem_diameter_fraction: 0.11,
};

pub const PRUNUS_PERSICA: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 3760,
    common_name: "Peach",
    scientific_name: "Prunus persica",
    growth_form: BotanicalGrowthForm::StoneFruitTree,
    symbolic_chromosomes: 8,
    max_height_mm: 16.0,
    canopy_radius_mm: 7.2,
    root_radius_mm: 5.0,
    leaf_efficiency: 1.02,
    root_uptake_efficiency: 0.93,
    water_use_efficiency: 0.82,
    volatile_scale: 1.08,
    fruiting_threshold: 0.70,
    litter_turnover: 0.94,
    shade_tolerance: 0.82,
    root_depth_bias: 0.56,
    symbiosis_affinity: 0.98,
    seed_mass: 0.115,
    fruit_rgb: [0.95, 0.60, 0.28],
    wood_density: 600.0,
    drag_coefficient: 0.48,
    stem_diameter_fraction: 0.11,
};

pub const PRUNUS_AVIUM: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 42229,
    common_name: "Sweet cherry",
    scientific_name: "Prunus avium",
    growth_form: BotanicalGrowthForm::StoneFruitTree,
    symbolic_chromosomes: 8,
    max_height_mm: 17.0,
    canopy_radius_mm: 7.0,
    root_radius_mm: 5.1,
    leaf_efficiency: 1.00,
    root_uptake_efficiency: 0.91,
    water_use_efficiency: 0.80,
    volatile_scale: 1.12,
    fruiting_threshold: 0.72,
    litter_turnover: 0.90,
    shade_tolerance: 0.80,
    root_depth_bias: 0.54,
    symbiosis_affinity: 0.96,
    seed_mass: 0.082,
    fruit_rgb: [0.66, 0.04, 0.08],
    wood_density: 600.0,
    drag_coefficient: 0.48,
    stem_diameter_fraction: 0.11,
};

pub const CITRUS_SINENSIS: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 2711,
    common_name: "Sweet orange",
    scientific_name: "Citrus sinensis",
    growth_form: BotanicalGrowthForm::CitrusTree,
    symbolic_chromosomes: 9,
    max_height_mm: 15.0,
    canopy_radius_mm: 6.6,
    root_radius_mm: 5.2,
    leaf_efficiency: 0.98,
    root_uptake_efficiency: 1.02,
    water_use_efficiency: 0.80,
    volatile_scale: 1.30,
    fruiting_threshold: 0.82,
    litter_turnover: 0.92,
    shade_tolerance: 0.92,
    root_depth_bias: 0.58,
    symbiosis_affinity: 1.00,
    seed_mass: 0.105,
    fruit_rgb: [0.96, 0.50, 0.10],
    wood_density: 550.0,
    drag_coefficient: 0.50,
    stem_diameter_fraction: 0.10,
};

pub const CITRUS_X_LIMON: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 2708,
    common_name: "Lemon",
    scientific_name: "Citrus x limon",
    growth_form: BotanicalGrowthForm::CitrusTree,
    symbolic_chromosomes: 9,
    max_height_mm: 14.5,
    canopy_radius_mm: 6.2,
    root_radius_mm: 5.1,
    leaf_efficiency: 0.96,
    root_uptake_efficiency: 1.01,
    water_use_efficiency: 0.78,
    volatile_scale: 1.36,
    fruiting_threshold: 0.80,
    litter_turnover: 0.90,
    shade_tolerance: 0.90,
    root_depth_bias: 0.56,
    symbiosis_affinity: 0.98,
    seed_mass: 0.096,
    fruit_rgb: [0.92, 0.82, 0.16],
    wood_density: 550.0,
    drag_coefficient: 0.50,
    stem_diameter_fraction: 0.10,
};

pub const BRACHYPODIUM_DISTACHYON: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 15368,
    common_name: "Purple false brome",
    scientific_name: "Brachypodium distachyon",
    growth_form: BotanicalGrowthForm::GrassClump,
    symbolic_chromosomes: 5,
    max_height_mm: 8.5,
    canopy_radius_mm: 3.0,
    root_radius_mm: 4.0,
    leaf_efficiency: 1.18,
    root_uptake_efficiency: 0.88,
    water_use_efficiency: 1.10,
    volatile_scale: 0.56,
    fruiting_threshold: 0.66,
    litter_turnover: 1.10,
    shade_tolerance: 0.58,
    root_depth_bias: 0.40,
    symbiosis_affinity: 0.72,
    seed_mass: 0.048,
    fruit_rgb: [0.78, 0.72, 0.34],
    wood_density: 200.0,
    drag_coefficient: 0.70,
    stem_diameter_fraction: 0.04,
};

pub const LEMNA_MINOR: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 4472,
    common_name: "Lesser duckweed",
    scientific_name: "Lemna minor",
    growth_form: BotanicalGrowthForm::FloatingAquatic,
    symbolic_chromosomes: 20,
    max_height_mm: 1.6,
    canopy_radius_mm: 2.8,
    root_radius_mm: 1.1,
    leaf_efficiency: 1.26,
    root_uptake_efficiency: 1.08,
    water_use_efficiency: 1.34,
    volatile_scale: 0.36,
    fruiting_threshold: 0.96,
    litter_turnover: 0.78,
    shade_tolerance: 1.10,
    root_depth_bias: 0.06,
    symbiosis_affinity: 0.54,
    seed_mass: 0.018,
    fruit_rgb: [0.68, 0.84, 0.30],
    wood_density: 100.0,
    drag_coefficient: 0.80,
    stem_diameter_fraction: 0.03,
};

pub const CERATOPHYLLUM_DEMERSUM: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 4428,
    common_name: "Coontail",
    scientific_name: "Ceratophyllum demersum",
    growth_form: BotanicalGrowthForm::SubmergedAquatic,
    symbolic_chromosomes: 12,
    max_height_mm: 15.0,
    canopy_radius_mm: 4.4,
    root_radius_mm: 1.0,
    leaf_efficiency: 1.18,
    root_uptake_efficiency: 0.68,
    water_use_efficiency: 1.30,
    volatile_scale: 0.34,
    fruiting_threshold: 0.92,
    litter_turnover: 0.82,
    shade_tolerance: 1.08,
    root_depth_bias: 0.04,
    symbiosis_affinity: 0.42,
    seed_mass: 0.022,
    fruit_rgb: [0.54, 0.72, 0.22],
    wood_density: 100.0,
    drag_coefficient: 0.80,
    stem_diameter_fraction: 0.03,
};

pub const ELODEA_CANADENSIS: BotanicalSpeciesProfile = BotanicalSpeciesProfile {
    taxonomy_id: 100364,
    common_name: "Canadian waterweed",
    scientific_name: "Elodea canadensis",
    growth_form: BotanicalGrowthForm::SubmergedAquatic,
    symbolic_chromosomes: 24,
    max_height_mm: 18.0,
    canopy_radius_mm: 4.8,
    root_radius_mm: 2.2,
    leaf_efficiency: 1.14,
    root_uptake_efficiency: 0.80,
    water_use_efficiency: 1.28,
    volatile_scale: 0.38,
    fruiting_threshold: 0.90,
    litter_turnover: 0.80,
    shade_tolerance: 1.04,
    root_depth_bias: 0.18,
    symbiosis_affinity: 0.46,
    seed_mass: 0.024,
    fruit_rgb: [0.62, 0.76, 0.26],
    wood_density: 100.0,
    drag_coefficient: 0.80,
    stem_diameter_fraction: 0.03,
};

const ALL_SPECIES: [BotanicalSpeciesProfile; 11] = [
    ARABIDOPSIS_THALIANA,
    MALUS_DOMESTICA,
    PYRUS_COMMUNIS,
    PRUNUS_PERSICA,
    PRUNUS_AVIUM,
    CITRUS_SINENSIS,
    CITRUS_X_LIMON,
    BRACHYPODIUM_DISTACHYON,
    LEMNA_MINOR,
    CERATOPHYLLUM_DEMERSUM,
    ELODEA_CANADENSIS,
];

pub fn botanical_species_profiles() -> &'static [BotanicalSpeciesProfile] {
    &ALL_SPECIES
}

pub fn species_profile_by_taxonomy(taxonomy_id: u32) -> Option<BotanicalSpeciesProfile> {
    ALL_SPECIES
        .iter()
        .copied()
        .find(|profile| profile.taxonomy_id == taxonomy_id)
}

pub fn sample_species_profile<R: Rng + ?Sized>(rng: &mut R) -> BotanicalSpeciesProfile {
    let idx = rng.gen_range(0..ALL_SPECIES.len());
    ALL_SPECIES[idx]
}
